### ISSUE TITLE
稀に何も選べていない状態が発生する

### ISSUE THREAD

**Issue by hieki** [hieki/oracle_button#10]
# WHAT
ポップアップウィンドウを開いた時に、どの音声も選択されていない現象が稀に発生する。
その場合、オラクルボタンを押しても何も音声が流れない。
厄介なことに、この現象の再現性は低い。

発生バージョン: 0.0.2

**Comment by Mic-U** [comment]
Chrome 最新版 (69.0.3497.92) で事象が発生することは確認したが、再現条件がさっぱりわからん...
何となく新規タブ作成時に発生率が高い気がする
引き続き調査

**Comment by hieki** [comment]
草

**Comment by Mic-U** [comment]
ポップアップを閉じてから約 15 秒操作せずに放置すると再現する。
今の所再現率は 100%
このタイミングで GC でも走ってるのか? ローカルストレージに保存すべきだろうか。

使用ブラウザ: Chrome 最新版 (69.0.3497.92)
