### ISSUE TITLE
ChromeExtentionの公開

### ISSUE THREAD

**Issue by hieki** [hieki/oracle_button#4]
- $5掛かる
  - それは別にいい
- Oracle社に訴えられる可能性がある
  - フォント及び色はOracle社のロゴとは異なるものを使用しているので、著作上の問題は無いはず
  - 緊急ORACLE機能の実装により、Oracle社のページに遷移するようになったのでOracle社とは無関係とは到底言い難くなってしまった

**Comment by remiria** [comment]
問答無用でリリースを断行しようと思い5ドル支払ったが公開時にエラーが出てしまい、エラーの詳細が一切表示されないので何もわからん…

**Comment by hieki** [comment]
なんか出来ました。 https://chrome.google.com/webstore/detail/oracle-button/jmhbndabpmenffegecmajddkhingckid?authuser=0
公開直後は404返ってきたりして大丈夫か……ってなったけど、これで誰もが幸せになれる……
